set -g set-titles on
set -g allow-rename on
setw -g automatic-rename off
set -g focus-events on

# Status line
set -g status-right-length 200


# if the path is longer than three directories, shorten it to only show the last three.
set -g status-right "#[fg=#606079]#(if [ \$(echo \"#{pane_current_path}\" | awk -F'/' '{print NF-1}') -gt 3 ]; then echo \"#{pane_current_path}\" | awk -F'/' '{print \"/…/\" \$(NF-2) \"/\" \$(NF-1) \"/\" \$NF}'; else echo \"#{pane_current_path}\"; fi)"

# General settings
set -g prefix C-f
set -g default-command "exec $SHELL -l"
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-environment -g XDG_CONFIG_HOME "$HOME/.config"
set -g @continuum-boot 'on'

set -g status on
set -g status-left ""
set -g status-interval 1
set -g status-bg default
set -g status-fg default

# Window name formatting
set -g window-status-format        '#[fg=#{?#{==:#I,0},#c48282,#{?#{==:#I,1},#6e94b2,#{?#{==:#I,2},#7fa563,#{?#{==:#I,3},#e8b589,#{?#{==:#I,4},#9bb4bc,#aeaed1}}}}}] #I:#W '
set -g window-status-current-format '#[bold]#[fg=#{?#{==:#I,0},#d8647e,#{?#{==:#I,1},#90a0b5,#{?#{==:#I,2},#7fa563,#{?#{==:#I,3},#e8b589,#{?#{==:#I,4},#9bb4bc,#cdcdcd}}}}}]⟦ #I:#W ⟧'

# Pane controls & navigation
bind v split-window -h
bind h split-window -v
bind x kill-pane

bind j command-prompt -p "Join window:" "join-pane -h -s ':%%'"
bind J command-prompt -p "Join window:" "join-pane -s ':%%'"
bind b command-prompt -p "Break to window:" "break-pane -d \; move-window -t %% \; display-message \"\""

bind-key -r -T prefix + resize-pane -U
bind-key -r -T prefix _ resize-pane -D
bind-key -r -T prefix - resize-pane -L
bind-key -r -T prefix = resize-pane -R

bind-key 0 select-window -t 0
bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4
bind-key 5 select-window -t 5
bind-key 6 select-window -t 6
bind-key 7 select-window -t 7
bind-key 8 select-window -t 8
bind-key 9 select-window -t 9

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

set -g update-environment "NVIM_LISTEN_ADDRESS"
set -g update-environment "NVIM_PWD"

set -g status-style default
