set -g @continuum-boot 'on'

set-option -g prefix C-f
# set-option -g prefix2 M-f
set -g default-command "exec $SHELL -l"
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-environment -g XDG_CONFIG_HOME "$HOME/.config"

set -g status on
set -g status-interval 1

set -g status-style fg=white,bg=black
# Show session name in the left section
set -g status-left " #{session_name}"

# Clear the right section
set -g status-right ""

# Set padding lengths to approximate centering
set -g status-left-length 100
set -g status-right-length 100

# Optional styling adjustments
set -g status-style "bg=default,fg=default"
set -g status-bg default
set -g status-fg default
#
#
bind v split-window -h
bind h split-window -v
#
bind x kill-pane

 # Allow tmux nvim to access remote nvim plugins
set -g update-environment "NVIM_LISTEN_ADDRESS"
#
#
set -g xterm-keys on
## Bind number keys to switch to window directly
bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4
bind-key 5 select-window -t 5
bind-key 6 select-window -t 6
bind-key 7 select-window -t 7
bind-key 8 select-window -t 8
bind-key 9 select-window -t 9
bind-key 0 select-window -t 10

bind-key -r -T prefix + resize-pane -U
bind-key -r -T prefix _ resize-pane -D
bind-key -r -T prefix - resize-pane -L
bind-key -r -T prefix = resize-pane -R

# # Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
