[window]
option_as_alt = "both"
decorations_theme_variant="Dark"
title = ""
dynamic_title=false
decorations="Buttonless"
padding = { x = 20, y = 20 }
dynamic_padding = true
opacity=0.85
blur=true

[font.normal]
family="JetBrainsMono Nerd Font Propo"

[font]
size = 17.0

[colors.primary]
background="#0c0c0d"
foreground = "#cdcdcd"

[colors.cursor]
text = "#141415"
cursor = "#cdcdcd"

[colors.normal]
black = "#141415"
red = "#d8647e"
green = "#7fa563"
yellow = "#e0a363"
blue = "#6e94b2"
magenta = "#bb9dbd"
cyan = "#9bb4bc"
white = "#cdcdcd"

[colors.bright]
black = "#606079"
red = "#c48282"
green = "#b4d4cf"
yellow = "#f3be7c"
blue = "#7e98e8"
magenta = "#aeaed1"
cyan = "#90a0b5"
white = "#c3c3d5"

[colors.search.matches]
foreground = "#141415"
background = "#405065"

[colors.selection]
background = "#333738"
foreground = "#cdcdcd"
