#!/bin/bash

# This is a sketchybarrc file that uses Lua scripts instead of Bash scripts

LUA_PLUGIN_DIR="$CONFIG_DIR/lua_plugins"
BASH_PLUGIN_DIR="$CONFIG_DIR/bash_plugins" # necessary for performance (example from demo, ensure this path is correct if you use it)
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Propo:17.0"
  label.font="JetBrainsMono Nerd Font:Propo:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/right_items.sh"
##### Force all scripts to run the first time #####
sketchybar --update
